import { Project } from '../../types/project';

export const cs50xWebProjects: Project[] = [
  {
    id: "cs50web-credit",
    title: "Credit",
    description: "This project involves implementing a program that validates credit card numbers using the Luhn algorithm and identifies the card type based on number patterns.",
    image: "/preview/credit.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-scrabble",
    title: "Scrabble",
    description: "A program that calculates and compares Scrabble scores of two players' words to determine the winner.",
    image: "/preview/scrabble.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-readability",
    title: "Readability",
    description: "A program that analyzes a block of text and estimates its U.S. grade-level readability using the Coleman-Liau index.",
    image: "/preview/readability.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-caesar",
    title: "Caesar",
    description: "A program that encrypts plaintext using Caesar's cipher, shifting each letter by a user-specified key.",
    image: "/preview/caesar.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-substitution",
    title: "Substitution",
    description: "A program that encrypts messages using a user-provided substitution cipher key to replace each letter with a corresponding one.",
    image: "/preview/substitution.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-plurality",
    title: "Pluratlity",
    description: "A program that calculates and compares Scrabble scores of two player's words to determine the winner.",
    image: "/preview/plurality.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-runoff",
    title: "Runoff",
    description: "A program that simulates an instant-runoff election using ranked-choice voting to determine the candidate with majority support.",
    image: "/preview/runoff.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-filter",
    title: "Filter",
    description: "A program that apply various filters (like grayscale, sepia, blur, and edge detection) to 24-bit BMP image files by manipulating pixel RGB values.",
    image: "/preview/filter.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-inheritance",
    title: "Inheritance",
    description: "A program that recursively simulates the inheritance of blood type alleles across generations in a family.",
    image: "/preview/inheritance.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-speller",
    title: "Speller",
    description: "A program that uses a hash table to implement an efficient spell checker by loading a dictionary and checking words in a text file.",
    image: "/preview/speller.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-dna",
    title: "DNA",
    description: "A program that identifies individuals based on DNA STR patterns by comparing sequences against a database.",
    image: "/preview/credit.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-trivia",
    title: "Trivia",
    description: "A web application that allows users to answer multiple-choice trivia questions using HTML, CSS, and JavaScript.",
    image: "/preview/trivia.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-homepage",
    title: "Homepage",
    description: "A simple static webpage about me.",
    image: "/preview/homepage.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-birthday",
    title: "Birthday",
    description: "A Flask-based web app that stores and displays users' friends' birthdays using a SQLite database.",
    image: "/preview/birthdays.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "cs50web-finance",
    title: "Finance",
    description: "A web application that simulates stock trading by allowing users to buy, sell, and track stock holdings with real-time prices.",
    image: "/preview/finance.png",
    tags: ["HTML", "CSS", "JavaScript"],
  },
];
