import { Project } from '../../types/project';

export const frontendProjects: Project[] = [
  {
    id: "facebook",
    title: "Facebook Clone UI",
    description: "A simple Facebook-style UI built from HTML/CSS/JS templates.",
    image: "/preview/facebook.jpg",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "facebook",
    video: "/videos/frontend/facebook.mp4",
  },
  {
    id: "instagram",
    title: "Instagram Clone UI",
    description: "An Instagram-style UI built from HTML/CSS/JS templates.",
    image: "/preview/instagram.jpg",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "instagram",
    video: "/videos/frontend/instagram.mp4",
  },
  {
    id: "x",
    title: "X Clone UI",
    description: "An X/Twitter-style UI built from HTML/CSS/JS templates.",
    image: "/preview/x.jpg",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "x",
    video: "/videos/frontend/x.mp4",
  },
  {
    id: "linkedin",
    title: "Linkedin UI",
    description: "A Linkedin-style UI built from HTML/CSS/JS templates.",
    image: "/preview/linkedin.png",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "linkedin",
    video: "/videos/frontend/linkedin.mp4",
  },
  {
    id: "youtube",
    title: "Youtube UI",
    description: "A Youtube-style UI built from HTML/CSS/JS templates.",
    image: "/preview/youtube.png",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "youtube",
    video: "/videos/frontend/youtube.mp4",
  },
  {
    id: "spotify",
    title: "Spotify UI",
    description: "A Spotify-style UI built from HTML/CSS/JS templates.",
    image: "/preview/spotify.png",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "spotify",
    video: "/videos/frontend/spotify.mp4",
  },
  {
    id: "amazon",
    title: "Amazon UI",
    description: "A Amazon-style UI built from HTML/CSS/JS templates.",
    image: "/preview/amazon.png",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "amazon",
    video: "/videos/frontend/amazon.mp4",
  },
  {
    id: "prmsuccit",
    title: "PRMSU CCIT",
    description: "A static website for the College of Communication and Information Technology of PRMSU.",
    image: "/preview/prmsuccit.jpg",
    tags: ["HTML", "CSS", "JavaScript"],
    ui: "prmsuccit",
    video: "/videos/frontend/prmsuccit.mp4",
  },
  {
    id: "tourism",
    title: "Philippine Tourism Website",
    description: "A tourism website for the Philippines, showcasing the country's attractions, culture, and history.",
    image: "/preview/tourism.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    ui: "tourism",
    video: "/videos/frontend/tourism.mp4",
  }
];
