import { Project } from '../../types/project';

export const webAppProjects: Project[] = [
  {
    id: "webapp-ai-consumption-tracker",
    title: "AI Consumption Tracker",
    description: "A web application for tracking and analyzing consumption data.",
    image: "/preview/consumption_tracker.png",
    tags: ["React", "Node.js", "Typescript", "Joy UI", "Sqlite3", "Prisma"],
    github: "https://github.com/joybernal/consumption_tracker",
    
  },
  {
    id: "webapp-lemonaddie",
    title: "Lemonaddie Website",
    description: "An end-to-end e-commerce platform featuring user accounts, product management, and seamless checkout, tailored for selling lifestyle goods.",
    image: "/preview/lemonaddie.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/lemonaddie-deploy",
    video: "/videos/web-apps/lemonaddie.mp4",
  },
  {
    id: "webapp-tripleq",
    title: "TripleQ Website",
    description: "A business website with integrated booking, service browsing, and project showcase functionality tailored for a modern construction firm.",
    image: "/preview/tripleq.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/tripleq-website",
    video: "/videos/web-apps/tripleq.mp4",
  },
  {
    id: "webapp-journal",
    title: "Journal Website",
    description: "A full stack journaling website that allows users to write, manage, and share personal entries with privacy controls and community features.",
    image: "/preview/journal.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/journal",
    video: "/videos/web-apps/journal.mp4",
  },
  {
    id: "webapp-ems",
    title: "Employee Management System",
    description: "A robust employee management system that handles onboarding, attendance, roles, and administrative operations for small to mid-sized businesses.",
    image: "/preview/ems.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/emsdeploy",
    video: "/videos/web-apps/ems.mp4",
  },
  {
    id: "webapp-bookstore",
    title: "Online Bookstore",
    description: "A full-featured e-commerce application focused on book discovery, user reviews, and personalized shopping experiences.",
    image: "/preview/books.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/bookit",
    video: "/videos/web-apps/bookstore.mp4",
  },
  {
    id: "webapp-writers",
    title: "Writers Website",
    description: "A website for writers to let their imagination run free.",
    image: "/preview/writershaven.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/writers-haven",
    video: "/videos/web-apps/writers.mp4",
  },
  {
    id: "webapp-memoria",
    title: "Memoria's Photography Studio",
    description: "A website for showcasing photography work and booking sessions.",
    image: "/preview/memoria.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/joybernal/memoria-photography",
    video: "/videos/web-apps/memoria.mp4",
  },
];
